# Generated by Django 5.2.4 on 2026-09-19 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0006_alter_barberapplication_id_alter_barberprofile_id_and_more'),
        ('bookings', '0003_bookingrequest_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='All services included in this booking', related_name='booking_requests', to='barbers.service'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Primary service (kept for backwards compatibility)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests_legacy', to='barbers.service'),
        ),
    ]
