# Generated by Django 5.2.4 on 2026-09-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingrequest_services_alter_bookingrequest_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20),
        ),
    ]
