# Generated by Django 6.1.1 on 2026-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='needs_chair_mirror',
            field=models.BooleanField(default=False, help_text='Whether customer requested barber to bring portable chair and mirror'),
        ),
    ]
