# Generated by Django 6.1.1 on 2026-09-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('service_mode', models.CharField(max_length=20)),
                ('service_radius', models.FloatField(default=5)),
                ('home_visit_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aadhaar_document', models.FileField(upload_to='barber_applications/aadhaar/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
