# Generated by Django 6.1.1 on 2026-09-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_barberapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberapplication',
            name='beard_home_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='barberapplication',
            name='beard_shop_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='barberapplication',
            name='haircut_home_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='barberapplication',
            name='haircut_shop_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
