# Generated by Django 5.2.4 on 2026-09-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_barberapplication_beard_home_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
