# Generated by Django 5.2.4 on 2026-09-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_alter_barberapplication_id_alter_barberprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='barber_profiles/'),
        ),
    ]
