# Generated by Django 5.2.4 on 2026-09-19 08:03

import barbers.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0005_barberprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BarberSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_duration', models.PositiveIntegerField(default=30, help_text='Duration per booking slot in minutes')),
                ('break_enabled', models.BooleanField(default=True, help_text='Whether the barber takes a daily break')),
                ('break_start', models.CharField(default='13:00', help_text='Break start time in HH:MM (24h)', max_length=10)),
                ('break_end', models.CharField(default='14:00', help_text='Break end time in HH:MM (24h)', max_length=10)),
                ('weekly_schedule', models.JSONField(blank=True, default=barbers.models.default_weekly_schedule)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='barbers.barberprofile')),
            ],
            options={
                'verbose_name': 'Barber Schedule',
                'verbose_name_plural': 'Barber Schedules',
            },
        ),
    ]
