# Generated by Django 5.2.4 on 2026-09-19 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0006_alter_barberapplication_id_alter_barberprofile_id_and_more'),
        ('bookings', '0005_alter_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='barbers.barberprofile')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='bookings.bookingrequest')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barber Review',
                'verbose_name_plural': 'Barber Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
