# Generated by Django 6.1.1 on 2026-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0007_barberreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberapplication',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard Barber'), ('premium', 'Premium Barber')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='barberapplication',
            name='provides_chair_mirror',
            field=models.BooleanField(default=False, help_text='Can provide portable chair and mirror for home visits'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard Barber'), ('premium', 'Premium Barber')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='provides_chair_mirror',
            field=models.BooleanField(default=False, help_text='Whether barber provides portable chair and mirror for home visits'),
        ),
    ]
