# Generated by Django 5.2.4 on 2026-10-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0008_barberapplication_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberapplication',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='barberapplication',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
